default_set: 'two-ubuntu-server-12042-x64'
sets:
  'two-ubuntu-server-12042-x64':
    default_node: 'first'
    nodes:
      'first':
        prefab: 'ubuntu-server-12042-x64'
        options:
                 ip: '10.11.12.2'
                 disk: 10
      'second':
        prefab: 'ubuntu-server-12042-x64'
        options:
                 ip: '10.11.12.3'
                 disk: 10
  'one-ubuntu-server-12042-x64':
    nodes:
      'first':
        prefab: 'ubuntu-server-12042-x64'
        options:
                 ip: '10.11.12.2'
                 disk: 10
